source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'

use_frameworks!

xcodeproj 'LUExpandableTableViewExample'
workspace '../LUExpandableTableView'

target :LUExpandableTableViewExample do
  pod 'LUExpandableTableView', :path => '../'

end
