source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'

use_frameworks!

xcodeproj 'LUExpandableTableViewExample'
workspace '../LUExpandableTableView'

target :LUExpandableTableViewExample do
  pod 'LUExpandableTableView', :path => '../'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

end
