source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target :LUExpandableTableViewExample do
  pod 'LUExpandableTableView', :path => '../'

end
